networks:
  internal:
    external: true

services:
  speaches:
    image: ghcr.io/speaches-ai/speaches:latest-cuda-12.6.3
    container_name: speaches
    restart: unless-stopped
    ports:
      - 8001:8000
    volumes:
      - /appdata/ai/hfmodels:/home/ubuntu/.cache/huggingface/hub
    networks:
      - internal
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://0.0.0.0:8000/health"] # TODO: won't work if a user changes the port
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  subgen:
    container_name: subgen
    image: ${SUBGEN_IMAGE:-mccloud/subgen:latest}
    restart: unless-stopped
    environment:
      WHISPER_MODEL_: ${SUBGEN_WHISPER_MODEL_:-arc-r/faster-whisper-large-zh-cv11}
      WHISPER_THREADS: ${SUBGEN_WHISPER_THREADS:-8}
      PROCADDEDMEDIA: True
      PROCMEDIAONPLAY: False
      NAMESUBLANG: ai
      SKIPIFINTERNALSUBLANG: eng
      WEBHOOKPORT: 9000
      CONCURRENT_TRANSCRIPTIONS: ${SUBGEN_CONCURRENT_TRANSCRIPTIONS:-1}
      WORD_LEVEL_HIGHLIGHT: False
      DEBUG: True
      TRANSCRIBE_DEVICE: cuda
      CLEAR_VRAM_ON_COMPLETE: False
      MODEL_PATH: ./models
      UPDATE: False
      APPEND: False
      USE_MODEL_PROMPT: False
      CUSTOM_MODEL_PROMPT:
      CUSTOM_REGROUP: ${SUBGEN_CUSTOM_REGROUP:-cm_sl=84_sl=42++++++1}
      SUBGEN_KWARGS: ${SUBGEN_SUBGEN_KWARGS}
    volumes:
      - /appdata/ai/subgen:/subgen/models
    ports:
      - "9000:9000"
    tty: true
    networks:
      - internal
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  subgen-korean:
    container_name: subgen-korean
    image: ${SUBGEN_KO_IMAGE:-mccloud/subgen:latest}
    restart: unless-stopped
    environment:
      WHISPER_MODEL_: ${SUBGEN_KO_WHISPER_MODEL_:-arc-r/faster-whisper-large-v2-Ko}
      WHISPER_THREADS: ${SUBGEN_KO_WHISPER_THREADS:-8}
      PROCADDEDMEDIA: True
      PROCMEDIAONPLAY: False
      NAMESUBLANG: ai
      SKIPIFINTERNALSUBLANG: eng
      WEBHOOKPORT: 9000
      CONCURRENT_TRANSCRIPTIONS: ${SUBGEN_KO_CONCURRENT_TRANSCRIPTIONS:-4}
      WORD_LEVEL_HIGHLIGHT: False
      DEBUG: True
      TRANSCRIBE_DEVICE: cuda
      CLEAR_VRAM_ON_COMPLETE: False
      MODEL_PATH: ./models
      UPDATE: False
      APPEND: False
      USE_MODEL_PROMPT: False
      CUSTOM_MODEL_PROMPT:
      CUSTOM_REGROUP: ${SUBGEN_KO_CUSTOM_REGROUP:-cm_sl=84_sl=42++++++1}
      SUBGEN_KWARGS: ${SUBGEN_KO_SUBGEN_KWARGS}
    volumes:
      - /appdata/ai/subgen:/subgen/models
    ports:
      - "9001:9000"
    tty: true
    networks:
      - internal
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  subgen-chinese:
    container_name: subgen-chinese
    image: ${SUBGEN_ZH_IMAGE:-mccloud/subgen:latest}
    restart: unless-stopped
    environment:
      WHISPER_MODEL_: ${SUBGEN_ZH_WHISPER_MODEL:-arc-r/faster-whisper-large-zh-cv11}
      WHISPER_THREADS: ${SUBGEN_ZH_WHISPER_THREADS:-8}
      PROCADDEDMEDIA: True
      PROCMEDIAONPLAY: False
      NAMESUBLANG: ai
      SKIPIFINTERNALSUBLANG: eng
      WEBHOOKPORT: 9000
      CONCURRENT_TRANSCRIPTIONS: ${SUBGEN_ZH_CONCURRENT_TRANSCRIPTIONS:-4}
      WORD_LEVEL_HIGHLIGHT: False
      DEBUG: True
      TRANSCRIBE_DEVICE: cuda
      CLEAR_VRAM_ON_COMPLETE: False
      MODEL_PATH: ./models
      UPDATE: False
      APPEND: False
      USE_MODEL_PROMPT: False
      CUSTOM_MODEL_PROMPT:
      CUSTOM_REGROUP: ${SUBGEN_ZH_CUSTOM_REGROUP:-cm_sl=84_sl=42++++++1}
      SUBGEN_KWARGS: ${SUBGEN_ZH_SUBGEN_KWARGS}
    volumes:
      - /appdata/ai/subgen:/subgen/models
    ports:
      - "9002:9000"
    tty: true
    networks:
      - internal
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  ollama:
    container_name: ollama
    tty: true
    restart: unless-stopped
    image: ollama/ollama:latest
    ports:
      - 11434:11434
    environment:
      OLLAMA_KEEP_ALIVE: ${OLLAMA_KEEP_ALIVE:-24h}
    volumes:
      - /appdata/ai/ollama:/root/.ollama
    networks:
      - internal
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
